"""add external product id

Revision ID: 0c054b46761a
Revises: abeef9d8c559
Create Date: 2026-08-12 20:56:19.322889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c054b46761a'
down_revision: Union[str, Sequence[str], None] = 'abeef9d8c559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_products_external_id'), 'products', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_external_id'), table_name='products')
    op.drop_column('products', 'external_id')
    # ### end Alembic commands ###
