"""add AI-ready product fields

Revision ID: abeef9d8c559
Revises: 33c971d65fdb
Create Date: 2026-08-12 18:25:21.312489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abeef9d8c559'
down_revision: Union[str, Sequence[str], None] = '33c971d65fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('features', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('target_audience', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('use_cases', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('material', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('search_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'search_text')
    op.drop_column('products', 'material')
    op.drop_column('products', 'color')
    op.drop_column('products', 'use_cases')
    op.drop_column('products', 'target_audience')
    op.drop_column('products', 'features')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'subcategory')
    # ### end Alembic commands ###
